export const TOGGLE_PUT_MODAL = 'TOGGLE_PUT_MODAL'

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'

export const PUT_TASK_REQUEST = 'PUT_TASK_REQUEST'
export const PUT_TASK_SUCCESS = 'PUT_TASK_SUCCESS'
export const PUT_TASK_ERROR = 'PUT_TASK_ERROR'

export const RESET_FIELD_ERROR = 'RESET_FIELD_ERROR'

export const CHANGE_PAGINATION = 'CHANGE_PAGINATION'